specs = ['Nurse Practitioner', 'General Surgery',
       'Certified Registered Nurse Anesthetist (CRNA)', 'Dermatology',
       'Optometry', 'Diagnostic Radiology', 'Physician Assistant',
       'Certified Clinical Nurse Specialist', 'Family Practice',
       'Registered Dietitian or Nutrition Professional', 'Psychiatry',
       'Gastroenterology', 'Obstetrics & Gynecology', 'Internal Medicine',
       'Licensed Clinical Social Worker', 'Psychologist, Clinical',
       'Otolaryngology', 'Emergency Medicine',
       'Advanced Heart Failure and Transplant Cardiology',
       'Anesthesiology', 'Neurology', 'Pulmonary Disease',
       'Physical Therapist in Private Practice', 'Orthopedic Surgery',
       'Medical Oncology', 'Nephrology',
       'Occupational Therapist in Private Practice', 'Audiologist',
       'Hematology-Oncology', 'Podiatry', 'Pathology', 'Endocrinology',
       'Urology', 'Physical Medicine and Rehabilitation', 'Hospitalist',
       'Nuclear Medicine', 'Cardiovascular Disease (Cardiology)',
       'Rheumatology', 'Geriatric Medicine', 'Ophthalmology',
       'Infectious Disease', 'Chiropractic', 'Cardiology', 'Neurosurgery',
       'Anesthesiology Assistant', 'General Practice',
       'Plastic and Reconstructive Surgery', 'Radiation Oncology',
       'Pediatric Medicine', 'Clinical Cardiac Electrophysiology',
       'Interventional Cardiology', 'Gynecological Oncology',
       'Thoracic Surgery', 'Surgical Oncology', 'Pain Management',
       'Hand Surgery', 'Allergy/ Immunology', 'Sleep Medicine',
       'Interventional Pain Management', 'Speech Language Pathologist',
       'Critical Care (Intensivists)', 'Oral Surgery (Dentists only)',
       'Vascular Surgery', 'Hematology', 'Sports Medicine',
       'Maxillofacial Surgery', 'Osteopathic Manipulative Medicine',
       'Cardiac Surgery', 'Interventional Radiology',
       'Undefined Physician type', 'Hospice and Palliative Care',
       'Dentist', 'Oral Surgery (Dentist only)',
       'Colorectal Surgery (Proctology)', 'Geriatric Psychiatry',
       'Clinical Cardiatric Electrophysiology', 'Preventive Medicine',
       'Addiction Medicine',
       'Hematopoietic Cell Transplantation and Cellular Therapy',
       'Certified Nurse Midwife']

states=['KY', 'TN', 'FL', 'NC', 'MA', 'NJ', 'PA', 'CT', 'OH', 'NV', 'LA',
       'IN', 'CA', 'ME', 'NY', 'ND', 'HI', 'NM', 'OK', 'WV', 'MI', 'MN',
       'MO', 'GA', 'ID', 'TX', 'AZ', 'VT', 'DC', 'VA', 'IL', 'MD', 'MT',
       'UT', 'AR', 'CO', 'WA', 'AK', 'AL', 'SC', 'NH', 'WI', 'NE', 'MS',
       'PR', 'WY', 'KS', 'DE', 'RI', 'OR', 'IA', 'SD', 'ZZ', 'GU', 'VI',
       'MP', 'AE']